/*
 * ============================================================================
 * GOLDEN RNG ENGINE - HEADER WITH SECURITY IMPROVEMENTS
 * ============================================================================
 * Cryptographic Random Number Generator Engine
 * Implements AUR3ES algorithm for cryptographic resistance
 * ============================================================================
 */

#ifndef RNG_ENGINE_H
#define RNG_ENGINE_H

#include <stdint.h>
#include <stddef.h>
#include <pthread.h>

/* ============================================================================
 * 1. CONFIGURATION
 * ============================================================================ */

/* Error codes for FIPS compliance */
#define RNG_ERROR_HEALTH_TEST_FAILED    -2
#define RNG_ERROR_STUCK_BITS            -3

typedef struct {
    int deterministic;           // Deterministic mode for testing
    int reseed_interval;        // Reseed interval
    int use_csprng;             // Use system CSPRNG (ALWAYS 1)
    int memory_locking;         // Lock memory
    int enable_fips_mode;       // Enable FIPS mode (CRNGCT) - Per NIST FIPS 140-2/3
} rng_config_t;

/* ============================================================================
 * 2. RNG HANDLE (OPAQUE)
 * ============================================================================ */

typedef struct rng_engine golden_rng_t;

/* ============================================================================
 * 3. RNG ENGINE API
 * ============================================================================ */

/**
 * @brief Create new RNG instance with AUR3ES
 * @param config Configuration (NULL for defaults)
 * @return RNG handle or NULL on error
 */
golden_rng_t* rng_create(const rng_config_t *config);

/**
 * @brief Set seed for deterministic mode
 * @param rng RNG handle
 * @param seed Seed buffer
 * @param seed_len Seed length
 * @return 0 on success, -1 on error
 */
int rng_set_seed(golden_rng_t *rng, const uint8_t *seed, size_t seed_len);

/**
 * @brief Destroy RNG instance
 * @param rng RNG handle
 */
void rng_destroy(golden_rng_t *rng);

/**
 * @brief Generate 256-bit block (4 x uint64_t)
 * @param rng RNG handle
 * @param output Array of 4 uint64_t for output
 */
void rng_generate_block(golden_rng_t *rng, uint64_t output[4]);

/**
 * @brief Generate raw bytes
 * @param rng RNG handle
 * @param buffer Output buffer
 * @param size Number of bytes
 */
void rng_generate_bytes(golden_rng_t *rng, unsigned char *buffer, size_t size);

/**
 * @brief Generate random uint64_t
 * @param rng RNG handle
 * @return Random 64-bit number
 */
uint64_t rng_uint64(golden_rng_t *rng);

/**
 * @brief Generate random uint32_t
 * @param rng RNG handle
 * @return Random 32-bit number
 */
uint32_t rng_uint32(golden_rng_t *rng);

/**
 * @brief Generate uniform double [0, 1)
 * @param rng RNG handle
 * @return Random double
 */
double rng_double(golden_rng_t *rng);

/**
 * @brief Generate normal distribution (Box-Muller)
 * @param rng RNG handle
 * @param mean Mean
 * @param stddev Standard deviation
 * @return Number with normal distribution
 */
double rng_normal(golden_rng_t *rng, double mean, double stddev);

/**
 * @brief Generate exponential distribution
 * @param rng RNG handle
 * @param lambda Lambda
 * @return Number with exponential distribution
 */
double rng_exponential(golden_rng_t *rng, double lambda);

/**
 * @brief Get RNG statistics
 * @param rng RNG handle
 * @param blocks_generated Blocks generated
 * @param reseeds_count Reseed counter
 * @param bytes_generated Bytes generated
 */
void rng_get_stats(golden_rng_t *rng, 
                   uint64_t *blocks_generated,
                   uint64_t *reseeds_count,
                   uint64_t *bytes_generated);

/**
 * @brief Force manual reseed
 * @param rng RNG handle
 */
void rng_reseed(golden_rng_t *rng);

/**
 * @brief Get default configuration
 * @return Default configuration
 */
rng_config_t rng_default_config(void);

/**
 * @brief Check if RNG is in deterministic mode
 * @param rng RNG handle
 * @return 1 if deterministic, 0 otherwise
 */
int rng_is_deterministic(golden_rng_t *rng);

/**
 * @brief Check if RNG uses CSPRNG
 * @param rng RNG handle
 * @return 1 if uses CSPRNG, 0 otherwise
 */
int rng_using_csprng(golden_rng_t *rng);

/**
 * @brief Run RNG self-test
 * @return 0 on success, -1 on error
 */
int rng_selftest(void);

/**
 * @brief Generate bytes in parallel using multiple threads
 * @param rng RNG handle
 * @param buffer Output buffer
 * @param size Number of bytes
 * @param num_threads Number of producer threads (0 for auto)
 * @return 0 on success, -1 on error
 */
int rng_generate_bytes_parallel(golden_rng_t *rng, unsigned char *buffer, size_t size, int num_threads);

/* ============================================================================
 * BENCHMARK DATA STRUCTURES
 * ============================================================================ */

/**
 * @brief Result of a benchmark execution
 */
typedef struct {
    double throughput_mbps;      // MB/s
    double time_seconds;         // Total time in seconds
    double speedup;             // Speedup vs sequential
    double efficiency;           // Efficiency (speedup/threads)
    size_t bytes_generated;      // Total bytes generated
    int threads_used;           // Threads used
    double confidence_low;       // 95% confidence interval lower bound
    double confidence_high;     // 95% confidence interval upper bound
} benchmark_result_t;

/**
 * @brief Complete benchmark report
 */
typedef struct {
    benchmark_result_t sequential;   // Sequential results
    benchmark_result_t parallel;     // Parallel results
    benchmark_result_t optimal;       // Best configuration found
    int optimal_threads;             // Optimal number of threads
    double best_speedup;             // Best speedup achieved
    const char* platform_info;       // Platform information
    size_t buffer_size;              // Buffer size tested
    int num_iterations;              // Iterations performed
} benchmark_report_t;

/**
 * @brief Benchmark configuration
 */
typedef struct {
    size_t buffer_size;          // Buffer size (0 for auto)
    int max_threads;            // Maximum threads to test
    int num_iterations;         // Iterations per test
    int quiet_mode;            // Quiet mode (less output)
} benchmark_config_t;

/**
 * @brief Run benchmark comparing parallel vs sequential generation
 * @param rng RNG handle
 * @param buffer_size Test buffer size in bytes (0 = auto: 10MB)
 * @param max_threads Maximum threads to test (0 = auto: detect cores)
 * @return 0 on success, -1 on error
 */
int rng_benchmark_parallel(golden_rng_t *rng, size_t buffer_size, int max_threads);

/**
 * @brief Run comprehensive benchmark with multiple configurations
 * @param rng RNG handle
 * @param config Benchmark configuration
 * @return Benchmark report (NULL on error)
 */
benchmark_report_t* rng_benchmark_comprehensive(golden_rng_t *rng, const benchmark_config_t *config);

/**
 * @brief Get default benchmark configuration
 * @return Default configuration
 */
benchmark_config_t rng_benchmark_default_config(void);

/**
 * @brief Print formatted benchmark report
 * @param report Report to print
 */
void rng_benchmark_print_report(const benchmark_report_t *report);

/**
 * @brief Free benchmark report memory
 * @param report Report to free
 */
void rng_benchmark_free_report(benchmark_report_t *report);

/**
 * @brief Get number of available CPU cores
 * @return Number of cores
 */
int rng_get_cpu_cores(void);

/* ============================================================================
 * SIMD FEATURES - Platform and CPU Detection
 * ============================================================================ */

/**
 * @brief Platform ID
 */
typedef enum {
    PLATFORM_UNKNOWN = 0,
    PLATFORM_X86_64,
    PLATFORM_ARM64,
    PLATFORM_X86,
    PLATFORM_ARM32
} platform_id_t;

/**
 * @brief Get platform ID
 * @return Platform ID
 */
platform_id_t get_platform_id(void);

/**
 * @brief Get platform name
 * @return Platform name as string
 */
const char* get_platform_name(void);

/**
 * @brief CPU features structure
 */
typedef struct {
    int has_sse2;
    int has_sse3;
    int has_ssse3;
    int has_sse4_1;
    int has_sse4_2;
    int has_avx;
    int has_avx2;
    int has_avx512f;
    int has_neon;
} cpu_features_t;

/**
 * @brief Detect CPU features
 * @param features Structure to fill
 */
void detect_cpu_features(cpu_features_t* features);

/**
 * @brief Get CPU features string
 * @return String with features
 */
const char* get_cpu_features_string(void);

/**
 * @brief Get optimal alignment for platform
 * @return Alignment bytes
 */
size_t get_optimal_alignment(void);

/**
 * @brief Check if little-endian
 * @return 1 if little-endian, 0 otherwise
 */
int is_little_endian(void);

/**
 * @brief Print system information
 */
void rng_print_system_info(void);

/**
 * @brief Basic AUR3ES benchmark
 */
void rng_benchmark_basic(void);

/* ============================================================================
 * SIMD BENCHMARK - Performance by Implementation
 * ============================================================================ */

/**
 * @brief SIMD benchmark result
 */
typedef struct {
    double scalar_throughput_mbps;
    double best_throughput_mbps;
    const char* best_implementation;
    cpu_features_t features;
} simd_benchmark_result_t;

/**
 * @brief Run benchmark comparing implementations
 * @param rng RNG handle
 * @param buffer_size Buffer size
 * @param iterations Iterations
 * @return Benchmark result
 */
simd_benchmark_result_t rng_benchmark_simd(golden_rng_t *rng, size_t buffer_size, int iterations);

/**
 * @brief Print SIMD benchmark report
 * @param report Report to print
 */
void rng_benchmark_simd_print_report(const simd_benchmark_result_t *report);

/* ============================================================================
 * BASE CRYPTOGRAPHIC FUNCTIONS (Exported for Tests)
 * ============================================================================ */

/**
 * @brief 64-bit left rotation
 */
uint64_t rotl64(uint64_t x, int k);

/**
 * @brief 64-bit right rotation
 */
uint64_t rotr64(uint64_t x, int k);

/**
 * @brief MurmurHash3 finalizer mix
 */
uint64_t mix64(uint64_t h);

/**
 * @brief Full AUR3ES state mix
 */
void full_state_mix(uint64_t state[8]);

/**
 * @brief State avalanche effect
 */
void enhanced_avalanche(uint64_t state[8]);

/* ============================================================================
 * MEMORY POOL - Optimization for Parallel Generation
 * ============================================================================ */

/**
 * @brief Pre-allocated memory pool for parallel generation
 */
typedef struct rng_memory_pool {
    unsigned char *buffer;      // Main pre-allocated buffer
    size_t buffer_size;         // Buffer size
    size_t used;                // Bytes used
    int num_blocks;             // Number of blocks in pool
    uint64_t *blocks;          // Pre-generated blocks
    pthread_mutex_t mutex;      // Mutex for thread-safe access
} rng_memory_pool_t;

/**
 * @brief Create memory pool
 * @param size Pool size in bytes
 * @return Pool or NULL on error
 */
rng_memory_pool_t* rng_memory_pool_create(size_t size);

/**
 * @brief Destroy memory pool
 * @param pool Pool to destroy
 */
void rng_memory_pool_destroy(rng_memory_pool_t *pool);

/**
 * @brief Get bytes from pool (generates more if needed)
 * @param pool Pool
 * @param rng RNG to generate new data
 * @param buffer Output buffer
 * @param size Bytes requested
 * @return 0 on success, -1 on error
 */
int rng_memory_pool_get(rng_memory_pool_t *pool, golden_rng_t *rng, 
                        unsigned char *buffer, size_t size);

/**
 * @brief Pre-generate data in pool
 * @param pool Pool
 * @param rng RNG
 * @param size Bytes to pre-generate
 * @return 0 on success, -1 on error
 */
int rng_memory_pool_prefill(rng_memory_pool_t *pool, golden_rng_t *rng, size_t size);

/* ============================================================================
 * SIMD IMPLEMENTATION - Accelerated Generation
 * ============================================================================ */

/**
 * @brief Generate bytes using SIMD when available
 * @param rng RNG handle
 * @param buffer Output buffer
 * @param size Bytes to generate
 * @return 0 on success, -1 on error
 */
int rng_generate_bytes_simd(golden_rng_t *rng, unsigned char *buffer, size_t size);

/**
 * @brief Check if SIMD is available
 * @return 1 if SIMD available, 0 otherwise
 */
int rng_simd_available(void);

/**
 * @brief Get name of active SIMD implementation
 * @return String name
 */
const char* rng_simd_implementation_name(void);

#endif /* RNG_ENGINE_H */
